---
#===============================================#
# Informações principais
#===============================================#
instituicao: Instituto Federal de Sergipe
author: José Alessandro Santos Santana
title: 'Sentilytics: Análise Automatizada de Sentimentos em Redes Sociais'
local: Lagarto - SE
date: '2025'
titulacao: Bacharelado
curso: Bacharelado em Sistemas de Informação
programa: ''
area_de_concentracao: Computação
linha_de_pesquisa: ''
coorientador: ''
orientador: 'Prof. Dr. Gilson Pereira dos Santos Júnior'
aprovacao_dia: '12/03/2025'
avaliador1: 'Prof. Me. George Leite Junior'
avaliador2: 'Prof. Me. Gustavo da Silva Quirino'
avaliador3: ''
incluir_ficha_catalografica: true
folha_de_aprovacao: true
#===============================================#
# Configurações de textos
#===============================================#
resumo: '@import(pages/resumo.md)'
abstract_texto: '@import(pages/abstract.md)'
proposito: '@import(pages/proposito.md)'
agradecimentos: '@import(pages/agradecimentos.md)'
resumen: ''
resume: ''
dedicatoria: ''
epigrafe: ''
capa_pdf_caminho: ''
#===============================================#
# Informações importantes
#===============================================#
siglas:
  - s: API
    d: Application Programming Interface
  - s: BPMN
    d: Business Process Model and Notation
  - s: CSV
    d: Comma-Separated Values
  - s: BERT
    d: Bidirectional Encoder Representations from Transformers
  - s: GPT
    d: Generative Pre-trained Transformer
  - s: AMQP
    d: Advanced Message Queuing Protocol
  - s: NLTK
    d: Natural Language Toolkit
  - s: VS Code
    d: Visual Studio Code
  - s: SSE
    d: Server-Sent Events
  - s: SQL
    d: Structured Query Language
  - s: JSON
    d: JavaScript Object Notation
  - s: AI
    d: Artificial Intelligence
  - s: VADER
    d: Valence Aware Dictionary and sEntiment Reasoner
  - s: XML
    d: Extensible Markup Language
simbolos:
graduacao: true
especializacao: false
mestrado: false
doutorado: false
tipo_do_trabalho: Monografia
projeto: true
apendices: false
anexos: false
errata: false
referencias_sistema: alf
lista_ilustracoes: true
lista_quadros: true
lista_tabelas: false
referencias_caminho: config/referencias.bib
palavras_chave: 'Análise de Sentimentos, Processamento de Linguagem Natural, Redes Sociais, Bluesky'
keywords: 'Sentiment Analysis, Natural Language Processing, Social Networks, Bluesky'
palabras_clave: ''
mots_cles: ''
#===============================================#
# Configurações para o limarka-render-html
# Link: https://github.com/ReinanHS/limarka-render-html
#===============================================#
page_render:
  published_time: '2025-03-12T00:35:50-03:00'
  instituicao_website: 'https://www.ifs.edu.br/'
  social_networks:
    facebook: ''
    instagram: ''
    twitter: ''
    github: Apolos7
  pages_render:
    - resumo.md
    - agradecimentos.md
  files_type:
    - pdf
    - tex
    - bib
  files_map:
    - "xxx-trabalho-academico.tex:trabalho-academico.tex"
    - "xxx-referencias.bib:referencias.bib"
---
